name: Windows Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.6.2
  ARTIFACT:     complexcalc-build.zip
  BUILD_TYPE:   Release

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qt3d
          setup-python: false       
              
      - name: (3) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
    
      - name: (4) Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: (5) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run:  |
              cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
              mkdir ${{ runner.temp }}\build
              cp ${{github.workspace}}\build\Release\ComplexCalc.exe ${{ runner.temp }}\build\ComplexCalc.exe
              cd ${{ runner.temp }}\build
              windeployqt6 --qmldir ${{ runner.temp }}\build ComplexCalc.exe --pdb --release --compiler-runtime
              rm -r tls
              rm -r networkinformation

      - name: (6) Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ComplexCalc
          path: ${{ runner.temp }}\build
