name: Windows Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.6.2
  ARTIFACT:     complexcalc.zip
  BUILD_TYPE:   Release

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qt3d
          setup-python: false       
              
      - name: (3) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
    
      - name: (4) Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: (5) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run:  |
              cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
              mkdir ${{ runner.temp }}\build
              cp ${{github.workspace}}\build\Release\ComplexCalc.exe ${{ runner.temp }}\build\ComplexCalc.exe
              cd ${{ runner.temp }}\build
              windeployqt6 --qmldir ${{ runner.temp }}\build ComplexCalc.exe --pdb --release --compiler-runtime
              rm -r tls
              rm -r networkinformation

      - name: (6) Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: complexcalc.zip
          directory: ${{ runner.temp }}
          path: ${{ runner.temp }}\build\*

      #- name: (Debugging) Print Directory Structure
      #  working-directory: ${{ runner.temp }}
      #  run: dir

      #- name: (Debugging) Create File
      #  working-directory: ${{ github.workspace }}
      #  run: copy NUL complexcalc.zip

      - name: (7) Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: (8) Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ runner.temp }}\complexcalc.zip
          asset_name: complexcalc.zip
          asset_content_type: application/zip
