name: Windows Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.6.2
  ARTIFACT:     complexcalc-build.zip
  BUILD_TYPE:   Release

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      #- name: (2) Get all tags for correct version determination
      #  working-directory:  ${{ github.workspace }}
      #  run: |
      #    git fetch --all --tags -f
      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qt3d
          setup-python: false

      - name: (4) Download JOM
        uses: suisei-cn/actions-download-file@v1
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

      - name: (5) Unzip JOM
        working-directory: ${{ runner.temp }}
        run:  |
              7z x jom.zip -ojom        
              
      - name: (7) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: (8) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run:  |
              cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
              mkdir ${{ runner.temp }}\build\
              cp ${{github.workspace}}\build\ComplexCalc.exe {{ runner.temp }}\build\ComplexCalc.exe
              ${{ runner.temp }}\jom\jom -j2
              cd ${{ runner.temp }}\build
              windeployqt --qmldir ${{ runner.temp }}\build ComplexCalc.exe --pdb --release --compiler-runtime
              
      - name: (9) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a qt-complexcalc-build.zip ${{ runner.temp }}\build\* -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
